apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dbdiky/guestbook.git
    targetRevision: HEAD
    path: stage
  destination:
    server: https://kubernetes.default.svc
    namespace: jackett

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

