apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
spec:
  selector:
    matchLabels:
      app: jackett
  replicas: 2
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
      - name: jacket
        image: linuxserver/jackett:latest
        ports:
        - containerPort: 9117


